# Generated by Django 3.0.4 on 2020-04-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0003_auto_20200331_1443'),
        ('company', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('body', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=800)),
                ('country', models.CharField(max_length=800)),
                ('category', models.CharField(max_length=800)),
                ('critical', models.CharField(max_length=800)),
                ('sid', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=15)),
                ('contact_service', models.CharField(blank=True, max_length=20, null=True)),
                ('message_to', models.CharField(max_length=14)),
                ('to_service', models.CharField(blank=True, max_length=20, null=True)),
                ('direction', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=300)),
                ('account_sid', models.CharField(max_length=50)),
                ('date_received', models.DateTimeField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Sms')),
            ],
        ),
    ]
