# Generated by Django 3.0.4 on 2020-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='category',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='critical',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
