# Generated by Django 3.0.4 on 2020-03-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200331_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.CharField(max_length=30),
        ),
    ]
