# Generated by Django 3.0.4 on 2020-04-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200402_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
