# Generated by Django 3.0.4 on 2020-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200402_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynumber',
            name='uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
