version: '3.7'

services:
  dockerapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      'ACCOUNT_SID': ''
      'AUTH_TOKEN': ''
      'SECRET_KEY': ''
      'DB_NAME': 'ethicalhabits'
      'DB_USER': 'postgres'
      'DB_PASSWORD': 'admin'
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:3.2.0
volumes:
  postgres_data:
