version: '3.7'

services:
  dockerapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      'ACCOUNT_SID': 'ACc822fc099d01e3a6d6e0197583e75b12'
      'AUTH_TOKEN': 'cb189b6130b0522cbc0dd055fa061fb9'
      'SECRET_KEY': '_+cxyxkxmq0==3ruk23)nti!!sy64fv(a9_)1dk71i-p(r-%ol'
      'DB_NAME': 'ethicalhabits'
      'DB_USER': 'postgres'
      'DB_PASSWORD': 'admin'
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:3.2.0
volumes:
  postgres_data:
