-
  hosts: all
  vars:
    - app_name: Woolworths
  name: Run playbook for {{ app_name }}
  tasks:
    - name: Install nginx
      dnf: name=nginx state=latest
  
    - name: Create nginx config file
      template: src=django_bootstrap.conf dest=/etc/nginx/conf.d/{{ app_name }}.conf
      become: yes
      notify:
        - restart nginx
        
  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted enabled=yes
      become: yes
