# Generated by Django 3.0.4 on 2020-03-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=300)),
                ('message_from', models.CharField(max_length=15)),
                ('from_service', models.CharField(blank=True, max_length=20, null=True)),
                ('message_to', models.CharField(max_length=14)),
                ('to_service', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(max_length=300)),
                ('direction', models.CharField(max_length=30)),
                ('account_sid', models.CharField(max_length=50)),
                ('created', models.DateTimeField(max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
