# Generated by Django 3.0.4 on 2020-03-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
