# Generated by Django 3.0.4 on 2020-03-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='body',
            field=models.CharField(max_length=800),
        ),
    ]
