# Generated by Django 3.0.4 on 2020-04-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200402_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='companyuser',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='middlename',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.CompanyUser'),
        ),
    ]
