# Generated by Django 3.0.4 on 2020-04-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_category'),
        ('employees', '0008_auto_20200402_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyUser',
            new_name='Employee',
        ),
    ]
