# Generated by Django 3.0.4 on 2020-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20200405_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
